package unscription;

import java.math.BigInteger; 
import java.security.MessageDigest; 
import java.security.NoSuchAlgorithmException;
import java.util.Random; 

public class UnsubscribeUsers { 
	public static String getMd5(String input) 
	{ 
		try { 
			MessageDigest md = MessageDigest.getInstance("MD5"); 
			byte[] messageDigest = md.digest(input.getBytes()); 
			BigInteger no = new BigInteger(1, messageDigest); 
			String hashtext = no.toString(16); 
			while (hashtext.length() < 32) { 
				hashtext = "0" + hashtext; 
			} 
			return hashtext; 
		} 
		catch (NoSuchAlgorithmException e) { 
			throw new RuntimeException(e); 
		} 
	} 

	public static void main(String args[]) throws NoSuchAlgorithmException 
	{ 
//		String salt = RandomStringUtils.randomAscii(255);
		String salt = "PS`Fig)?4L]~[1OS1s3uz:kM;`;PulK*Lt/+:Qsk}][O*-WsR^./ITz`?H'4oj[rB#_'79u7i&ul(x`';65Em'HCbWH'{s3K.0Pq~5+!F$7oUt}ar)'x&9I=jrA}GtJp8mXsu-`Ru?Us,u*A$=~RQ}L]m`:h'$)|L!rXXpoJ(tLO$6*PYu+de8$`m~sZc5Y7=hGZg=;aI._&i3eEU6PlO?nG%{+!!_y2'y0WTO37;.,;'}+zbiN59xnmL|7o";
		//for deactive user
		String s = "83583385" + ":"+ salt;
		//for delete user
		//String s = "82831922" + ":" + "qa26@yopmail.com" + ":" + salt;
		System.out.println("Your HashCode Generated by MD5 is: " + getMd5(s));
		if(!("a".equals("a") || "b".equals("b"))) {
			System.out.println("dasda");
		}
	} 
} 
